spring:
  application:
    name: docker-registry
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai

server:
  port: 8080
  servlet:
    context-path: ""

# 通用配置
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.diy: DEBUG

# 分片上传配置
docker-registry:
  upload:
    session-timeout: 1800 # 上传会话超时时间（秒）
    cleanup-interval: 300 # 清理间隔（秒）
    max-chunk-size: 10485760 # 最大块大小 10MB
