spring:
  application:
    name: docker-registry
  profiles:
    # 本地开发使用 local 配置（包含真实密钥，不会提交到Git）
    # 生产环境使用 dev 或 linux 配置（需要环境变量）
    active: local
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai

server:
  port: 8080
  servlet:
    context-path: ""

# 通用配置
logging:
  pattern:
    # 彩色控制台输出格式
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%p]){highlight} %clr([%t]){faint} %clr(%logger{39}){cyan} %clr(:){faint} %m%n"
  level:
    root: INFO
    com:
      diy:
        mapper: debug # MyBatis SQL日志
        service: info # Service层日志
        controller: info # Controller层日志
        config: info # 配置类日志

# 分片上传配置
docker-registry:
  upload:
    session-timeout: 1800 # 上传会话超时时间（秒）
    cleanup-interval: 300 # 清理间隔（秒）
    max-chunk-size: 10485760 # 最大块大小 10MB
