# Windows开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/docker_registry?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: diy
    password: diy # 请修改为你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-test-query: SELECT 1

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 阿里云OSS配置（开发环境）
aliyun:
  oss:
    enabled: true
    endpoint: https://oss-cn-beijing.aliyuncs.com # 北京地区
    bucket-name: tyjbmembpsjoLUyBJxtqT5knH7RZV0
    access-key-id: LTAI5tSVRKd1pvQiXCVAZ3Ub
    access-key-secret: tyjbmembpsjoLUyBJxtqT5knH7RZV0
    # 路径前缀配置
    blob-prefix: dev-blobs/ # 开发环境blob存储路径前缀
    temp-prefix: dev-temp/ # 开发环境临时文件路径前缀

logging:
  level:
    com.diy: DEBUG
    com.diy.mapper: DEBUG
